# Travis CI script

language: cpp

os:
- linux
#- osx

dist: trusty

cache: ccache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

env:
  matrix:
    - ZMQ_VERSION=4.2.5
    - ZMQ_VERSION=4.2.4

matrix:
  include:
    ##########################################################
    # Clang on OSX
    # Travis takes longer to start OSX instances,
    # so leaving it first for the overall build to be faster.
    ##########################################################
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install cmake" ZMQ_VERSION=4.2.5 DRAFT=1
  # - env: BUILD_TYPE=cmake DO_CLANG_FORMAT_CHECK=1 CLANG_FORMAT=/usr/local/clang-5.0.0/bin/clang-format
    # os: linux
    # addons:
    # apt:
      # sources:
        # - llvm-toolchain-trusty-5.0
      # packages:
        # - clang-5.0
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" ZMQ_VERSION=4.2.5 DRAFT=1

sudo: required

before_install:
  - pip install --user cpp-coveralls

# Build and check this project
script:
  - eval "${MATRIX_EVAL}"
  - cmake --version
  - ./ci_build.sh

after_success:
  - coveralls --root . -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/" -E ".*demo/" -E ".*libzmq/"
